@startuml chat-module

set separator ::

interface AltV.Atlas.Chat::IChat {
    + <<delegate>> ChatMessageDelegate(IPlayer player, string message) : void
    + <<delegate>> ChatMessageAsyncDelegate(IPlayer player, string message) : Task

    + <<event>> OnChatMessage() : ChatMessageDelegate
    + <<event>> OnChatMessageAsync() : ChatMessageDChatMessageAsyncDelegateelegate
}

class AltV.Atlas.Chat::Chat implements AltV.Atlas.Chat::IChat {
    - _logger : ILogger<Chat>
    - OnChatParser(IPlayer player, MValueConst[ ] mValueArray, Action<IPlayer, string> action) : void
    - OnChat( IPlayer player, string message ) : void
    + <<ctor>> Chat(ILogger<Chat> logger)
}

class AltV.Atlas.Chat::ChatModule <<static>> {
    ~ <<static>> EventName : string

    + <<static>> RegisterChatModule(\n\tthis IServiceCollection services,\n\tstring eventName = "chat:message"\n) : IServiceProvider
    + <<static>> InitializeChatModule(this IServiceProvider serviceProvider) : IServiceProvider
}

class AltV.Atlas.Chat::ChatExtensions <<static>> {
    + <<static>> SendChatMessage(this IPlayer player, string message) : void
    + <<static>> SendChatMessageToAll(this IPlayer sender, string message) : void
    + <<static>> SendChatMessageToAll( string message ) : void
}

@enduml